### ISSUE TITLE
TypeError: request() got an unexpected keyword argument 'json'

### ISSUE THREAD

**Issue by pataquets** [healthchecks/hchk#1]
Ubuntu Trusty

```
$ sudo pip install hchk
Downloading/unpacking hchk
  Downloading hchk-0.1.2.tar.gz
  Running setup.py (path:/tmp/pip_build_root/hchk/setup.py) egg_info for package hchk

Requirement already satisfied (use --upgrade to upgrade): click in /usr/local/lib/python2.7/dist-packages (from hchk)
Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages (from hchk)
Installing collected packages: hchk
  Running setup.py install for hchk

    Installing hchk script to /usr/local/bin
Successfully installed hchk
Cleaning up...

$ hchk 
Usage: hchk [OPTIONS] COMMAND [ARGS]...

  A CLI interface to healthchecks.io

Options:
  --help  Show this message and exit.

Commands:
  ping    Create a check if neccessary, then ping it.
  setkey  Save API key in $HOME/.hchk

$ hchk setkey [SCRUBBED]
API key saved!
```

The API key is, indeed, saved into the `.hchk` file, as I checked by cat'ing it.

Later, when I copy/pasted the example command:

```
$ hchk ping -n "My New Check" -t "web prod" -p 600 -g 60
Traceback (most recent call last):
  File "/usr/local/bin/hchk", line 9, in <module>
    load_entry_point('hchk==0.1.2', 'console_scripts', 'hchk')()
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 664, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 644, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 991, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 837, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python2.7/dist-packages/click/core.py", line 464, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hchk/cli.py", line 101, in ping
    url = get_ping_url(kwargs)
  File "/usr/local/lib/python2.7/dist-packages/hchk/cli.py", line 69, in get_ping_url
    r = requests.post(url, json=payload).json()
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 88, in post
    return request('post', url, data=data, **kwargs)
  File "/usr/lib/python2.7/dist-packages/requests/api.py", line 44, in request
    return session.request(method=method, url=url, **kwargs)
TypeError: request() got an unexpected keyword argument 'json'
```

**Comment by cuu508** [comment]
Thanks for report! This is likely because of the older requests library in Trusty. Will fix this.

**Comment by cuu508** [comment]
This should be fixed now, tested on Trusty. 
On Python < 2.7.9 you'll see SSL-related warnings when creating a new check. I'm not sure yet how to best fix these. Meanwile, Python 3 works:

```
sudo apt-get install python3-pip
sudo pip3 install hchk
hchk ping
```

**Comment by pataquets** [comment]
Finally got around to test it and I can confirm it's fixed (installing via pip2), thank you very much.
However, I haven't seen any SSL-related warning.

**Comment by p00j4** [comment]
2.7.6 also it doesn't work,  works on my 2.7.11
